-- Real PageSpeed Insights audits.
--
-- Adds the provenance, field-data and finding metadata needed to store what
-- Google actually returned, and marks every pre-existing row as simulated so
-- the two can never be confused.

-- --------------------------------------------------------------- provenance
create type public.audit_provider as enum ('pagespeed', 'simulated');
create type public.finding_kind as enum ('opportunity', 'diagnostic');
create type public.crux_category as enum ('FAST', 'AVERAGE', 'SLOW', 'NONE');
create type public.field_scope as enum ('url', 'origin');

alter table public.audits
  -- Existing rows predate the live integration and were generated, not measured.
  add column provider public.audit_provider not null default 'simulated',

  -- What was asked for, and where Google actually ended up after redirects.
  add column requested_url text,
  add column final_url text,

  add column lighthouse_version text,
  -- Google's own analysis timestamp, which is not the same as when we stored it.
  add column analysed_at timestamptz,

  -- The untouched provider response, so a stored audit can always be
  -- re-derived without re-running it.
  add column raw_response jsonb,

  -- Machine-readable failure cause, alongside the human failure_reason.
  add column error_code text check (char_length(error_code) <= 64),

  -- ---- CrUX field data. All null when Google reports no field data. -------
  add column field_data_available boolean not null default false,
  add column field_scope public.field_scope,
  add column field_overall_category public.crux_category,
  add column field_lcp_ms integer check (field_lcp_ms >= 0),
  add column field_inp_ms integer check (field_inp_ms >= 0),
  add column field_cls numeric(6, 3) check (field_cls >= 0),
  add column field_fcp_ms integer check (field_fcp_ms >= 0),
  add column field_ttfb_ms integer check (field_ttfb_ms >= 0);

comment on column public.audits.provider is
  'pagespeed = measured by Google. simulated = generated by the retired mock engine.';
comment on column public.audits.raw_response is
  'Verbatim PageSpeed Insights response. Large (typically 300KB-1MB per run).';
comment on column public.audits.analysed_at is
  'lighthouseResult.fetchTime — when Google ran the analysis.';

-- New live audits must record where they came from; simulated ones cannot be
-- created any more, so only pagespeed rows are required to carry provenance.
alter table public.audits
  add constraint audits_pagespeed_has_provenance check (
    provider <> 'pagespeed'
    or status <> 'completed'
    or (requested_url is not null and raw_response is not null)
  );

-- Field metrics only make sense when field data was actually reported.
alter table public.audits
  add constraint audits_field_metrics_require_availability check (
    field_data_available
    or (
      field_scope is null
      and field_overall_category is null
      and field_lcp_ms is null
      and field_inp_ms is null
      and field_cls is null
      and field_fcp_ms is null
      and field_ttfb_ms is null
    )
  );

create index audits_provider_idx on public.audits (owner_id, provider);

-- Powers duplicate-run protection and rate limiting without a table scan.
create index audits_owner_created_idx on public.audits (owner_id, created_at desc);

-- ------------------------------------------------------------------ findings
alter table public.issues
  add column kind public.finding_kind not null default 'diagnostic',
  -- Lighthouse's own summary line, e.g. "Potential savings of 1.2 s".
  add column display_value text check (char_length(display_value) <= 200),
  -- Measured saving Lighthouse attributes to fixing this, when it reports one.
  add column savings_ms integer check (savings_ms >= 0),
  add column provider public.audit_provider not null default 'simulated';

comment on column public.issues.savings_ms is
  'Lighthouse overallSavingsMs. Null when Lighthouse did not estimate a saving.';

-- `affected_pages` held invented page paths under the mock engine. Real runs
-- store the specific resource URLs Lighthouse flagged, so widen the cap.
alter table public.issues
  drop constraint if exists issues_affected_pages_check;
alter table public.issues
  add constraint issues_affected_pages_check check (cardinality(affected_pages) <= 25);

create index issues_provider_idx on public.issues (owner_id, provider);

-- ------------------------------------------------------- retire the simulator
-- Existing data stays put. It is relabelled, not deleted: removing it is an
-- explicit, confirmed action in the application, not a silent side effect of a
-- migration.
update public.audits set provider = 'simulated' where provider is distinct from 'simulated';
update public.issues set provider = 'simulated' where provider is distinct from 'simulated';

-- New rows are live unless something deliberately says otherwise.
alter table public.audits alter column provider set default 'pagespeed';
alter table public.issues alter column provider set default 'pagespeed';
